config/routes.rb
GeoReplay::Application.routes.draw do
  devise_for :users

  resources :replays do
	  member do
		  get 'appdata'
	  end
  end

  root :to => "replays#index"

end

app/models/replay.rb
class Replay < ActiveRecord::Base
	validates :name, :desc, :userId, :statusId, :presence => true
  attr_accessible :replayId, :attribution, :dataPath, :desc, :length, :name, :screenshotPath, :source, :statusId, :userId
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/replays_controller.rb
class ReplaysController < ApplicationController
  # --------------------------------------------------------------
  # HOME PAGE
  #     GET /replays
  #
  def index
    @replays = Replay.where('statusId>0')
    render
  end

  # --------------------------------------------------------------
  # SHOW
  #    GET /replays/1
  # regular view of replay
  #
  def show

    begin
	    @replay = Replay.find(params[:id])
    rescue
	    flash[:error] = "sorry, no such replay"
	    redirect_to :root
	    return
    end


    # make sure this user can see this replay
    if (@replay.statusId == "0") and (@replay.userId!=current_user.id)
	flash[:notice] = "sorry, can't show you specified replay"
	redirect_to :back
	return
    end

    if @replay.dataPath == ''
	flash[:notice] = "no dataPath associated with replay"
	redirect_to :back
	return
    end

    begin
	    @replaydata = File.read(@replay.dataPath)
    rescue
	    flash[:notice] = "invalid dataPath associated with replay"
	    redirect_to :back
	    return
    end

    # able to retreve the appData file, so render the view
    render :layout => "appWithMap"
  end

  # --------------------------------------------------------------
  # NEW
  #
  #     GET /replays/new
  # 
  # This is called when the "New Replay" link in the header is clicked
  #
  def new
    @replay = Replay.new
    begin
        @path=Rails.root.to_s+"/public/appdata/replay_empty.json"
        logger.info "try to read #{@path}"
	    @replaydata = File.read("#{@path}")
    rescue
	    flash[:notice] = "cannot find blank replay JSON file"
	    redirect_to :back
	    return
    end
    render "edit", :layout => "appWithMap"
  end

  # --------------------------------------------------------------
  # EDIT
  #
  #     GET /replays/1/edit
  #
  def edit
    @replay = Replay.find(params[:id])
    if @replay.dataPath == ''
	flash[:notice] = "no dataPath associated with replay"
	redirect_to :back
	return
    end

    begin
	    @replaydata = File.read(@replay.dataPath)
    rescue
	    flash[:notice] = "invalid dataPath associated with replay"
	    redirect_to :back
	    return
    end
    render :layout => "appWithMap"
  end

  # --------------------------------------------------------------
  # CREATE
  #
  #     POST /replays
  #
  # Called by edit view when there's no app ID
  #
  def create
	@replay = Replay.new()
	@data=request.filtered_parameters
	@replay.name=@data['appName']
	@replay.desc=@data['appDescription']
	@replay.source=@data['sources']
	@replay.attribution=@data['author']
	@replay.userId=current_user.id
	@replay.length=@data['animLength']
	@replay.screenshotPath=''
	@replay.dataPath=''
	@replay.statusId=@data['status']=="1" ? 1 : 0
	logger.debug "request: #{request}"
	logger.debug "data: #{@data}"

    respond_to do |format|   # should be a JSON request
      if @replay.save
	@filePath='/appdata/replay_'+@replay.id.to_s()+'.json'
	@replay.dataPath='public'+@filePath
	@data['dataPath']=@replay.dataPath
	@data['id']=@replay.id
	@jsondata=@data.to_json(:except => ['controller','replay', 'action'])
	logger.debug "data: "+@jsondata
	begin  # try to create the appdata file
	   logger.debug "trying to write file: "+Rails.public_path+@filePath
	   File.open(Rails.public_path+@filePath, 'w') {|f| f.write(@jsondata) }
   	   Replay.update(@replay.id,"dataPath"=>@replay.dataPath) # update DB with filename
	rescue
	   format.html { redirect_to @replay, notice: 'unable to write appdata json.' }
	   format.json { render json: @replay, status: 'unable to write appdata json.' }
	end
	# create and write succeeded
        format.html { redirect_to @replay, notice: 'Replay was successfully created.' }
        format.json { render json: @replay, status: :created, location: @replay }
      else # create failed
        format.html { render action: "new" }
        format.json { render json: @replay.errors, status: :unprocessable_entity }
      end
    end
  end

  # --------------------------------------------------------------
  # UPDATE
  #
  #    PUT /replays/1
  #
  # hit from edit view when ID is non-zero
  #
  def update
    	@replay = Replay.find(params[:id])
	@data=request.filtered_parameters
	logger.debug "data: #{@data}"

	if @replay.userId!=current_user.id  # only let right user update replay
	   render json: @replay, status: 'not permitted'
	end

    respond_to do |format|   # should be a JSON request
      if Replay.update(@replay.id, :name=>@data['appName'],
			:desc=>@data['appDescription'],
			:source=>@data['sources'],
			:attribution=>@data['author'],
			:length=>@data['animLength'],
			:statusId=>@data['status']=="1" ? 1 : 0)
	@filePath='/appdata/replay_'+@replay.id.to_s()+'.json' # dropping off the /public part
	@data['dataPath']=@replay.dataPath # make sure user doesn't screw it up
	@jsondata=@data.to_json(:except => ['controller','replay', 'action', 'updated_at', 'userId'])
	logger.debug "data to save: "+@jsondata
	begin  # try to create the appdata file
	   logger.debug "trying to write file: "+Rails.public_path+@filePath
	   File.open(Rails.public_path+@filePath, 'w') {|f| f.write(@jsondata) }
	rescue
	   format.html { redirect_to @replay, notice: 'unable to write appdata json.' }
	   format.json { render json: @replay, status: 'unable to write appdata json.' }
	end
	# create and write succeeded
        format.html { redirect_to @replay, notice: 'Replay was successfully created.' }
        format.json { render json: @replay, status: :created, location: @replay }
      else # create failed
        format.html { render action: "new" }
        format.json { render json: @replay.errors, status: :unprocessable_entity }
      end
    end
  end

# --------------------------------------------------------------
# DELETE
#
# removes chosen replay
#
# DELETE /replays/1
# DELETE /replays/1.json
  def destroy
    @replay = Replay.find(params[:id])
    @replay.destroy

    respond_to do |format|
      format.html { redirect_to replays_url }
      format.json { head :no_content }
    end
  end

  # GET /replays/1/appData
  # returns JSON data
  def appdata
    @replay = Replay.find(params[:id])

    if @replay.dataPath != ''
	    begin
		    render :file => @replay.dataPath
	    rescue
		    render :inline => "{error: 'unable to open dataPath'}"
	    end
    else
	    render :inline => "{error: 'no dataPath'}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
	    case level
		when :notice then "alert alert-info"
		when :success then "alert alert-success"
		when :error then "alert alert-error"
		when :alert then "alert alert-error"
	    end
	end
end

app/helpers/replays_helper.rb
module ReplaysHelper
end

app/views/layouts/appWithMap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeoReplay</title>
  <%= stylesheet_link_tag "application", :media => "screen" %>
  <%= stylesheet_link_tag "bootstrap.min", :media => "screen" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?v=3.9&key=AIzaSyCCj-fR4vd7d0Ipp3lh5EnvEyVWs2uXRDc&sensor=false&libraries=drawing">
  </script>
  <%= javascript_include_tag "elabels3" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= javascript_include_tag "bootstrap.min" %>
<div class="row-fluid">
	<div id="headerRow" class="span12"><table width="100%"><tr><td width="70%" align="left" valign="center"><%= link_to "Geo Replay", replays_path, { :class=>"headerLink bigtext" } %> <%= image_tag "history_replay_logo.png" %></td><td width="30%" align="right">
<% if user_signed_in? %>
	<%= link_to('New Replay', new_replay_path, {:class=>"headerLink" }) %> /
	<%= link_to('Logout', destroy_user_session_path, {:method => :delete, :class=>"headerLink" }) %> /
  <%= link_to('Account', edit_user_registration_path, { :class=>"headerLink" }) %>
<br/>
<div class="small-text">Logged in as <%= current_user.email %></div>
<% else %>
  <%= link_to('Login', new_user_session_path, { :class=>"headerLink" })  %> /
  <%= link_to('Register', new_user_registration_path, { :class=>"headerLink" })  %>
<% end %>
</td></tr></table>
   </div>
</div>

<div style="padding-left: 5pt;">

  <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
  <% end %>

<%= yield %>

</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeoReplay</title>
  <%= stylesheet_link_tag "application", :media => "screen" %>
  <%= stylesheet_link_tag "bootstrap.min", :media => "screen" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= javascript_include_tag "bootstrap.min" %>
<div class="row-fluid">
	<div id="headerRow" class="span12"><table width="100%"><tr><td width="70%" align="left" valign="center"><%= link_to "Geo Replay", replays_path, { :class=>"headerLink bigtext" } %> <%= image_tag "history_replay_logo.png" %></td><td width="30%" align="right">
<% if user_signed_in? %>
	<%= link_to('New Replay', new_replay_path, {:class=>"headerLink" }) %> /
	<%= link_to('Logout', destroy_user_session_path, {:method => :delete, :class=>"headerLink" }) %> /
  <%= link_to('Account', edit_user_registration_path, { :class=>"headerLink" }) %>
<br/>
<div class="small-text">Logged in as <%= current_user.email %></div>
<% else %>
  <%= link_to('Login', new_user_session_path, { :class=>"headerLink" })  %> /
  <%= link_to('Register', new_user_registration_path, { :class=>"headerLink" })  %>
<% end %>
</td></tr></table>
   </div>
</div>

<div style="padding-left: 5pt;">

  <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
  <% end %>

<%= yield %>
</div>
</body>
</html>

app/views/replays/edit.html.erb
<%= javascript_tag do %>
	var replayData=<%= raw @replaydata %>;
<% end %>

<%= javascript_include_tag "replay_edit" %>
<div style="padding-top: 5px;">
<%= form_tag("/update", :method => "post" ) do %>
		<div class="row-fluid">
		   <div id="appRow" class="span7">
			   <div class="row-fluid"> <!-- app data header -->
				   <div class="span2" align="right"><div class="formlabel">Replay Name</div></div>
				   <div class="span4"><input type="text" id="appName" class="input-block-level" onchange="setAppFieldValue('appName')"/></div>
				   <div class="span3" align="right"><button type="button" id="saveButton" onclick="saveReplay()">Save Replay</button></div>
				   <div class="span3"><button type="button" name="runButton" onclick="runReplay();">Preview Replay</button></div>
			   </div>
			   <div class="row-fluid"> <!-- app data header -->
				   <div id="appDetails" class="span2" align="right">
					   <a data-toggle="collapse" data-target="#appDataDiv" onclick="changeCollapseIcon();"><i class="icon-chevron-down"></i><strong>Details</strong></a>
				   </div>
				   <div class="span10"><hr></div>
			   </div>
			   <div id="appDataDiv" class="collapse in"> <!-- app data fields -->
				   <div class="row-fluid">
					   <div class="span2" align="right"><div class="formlabel">Map Type</div></div>
					   <div class="span4"><select id="mapType" class="input-block-level" onchange="setMapType()"><option value="terrain">Terrain</option><option value="satellite">Satellite</option><option value="roadmap">Roadmap</option><option value="hybrid">satellite+roadmap</option></select></div>
					   <div class="span2" align="right"><div class="formlabel">Map Features</div></div>
					   <div class="span4"><select id="mapStyle" class="input-block-level" onchange="setMapStyle()"><option value="normal">Normal</option><option value="min">No roads</option></select></div>
				   </div>
				   <div class="row-fluid">
					   <div class="span2" align="right"><div class="formlabel">Description</div></div>
					   <div class="span10"><textarea id="appDescription" rows="1" class="input-block-level" onchange="setAppFieldValue('appDescription')"></textarea></div>
				   </div>
				   <div class="row-fluid">
					   <div class="span2" align="right"><div class="formlabel">Sources</div></div>
					   <div class="span10"><textarea id="sources" rows="1" class="input-block-level" onchange="setAppFieldValue('sources')"></textarea></div>
				   </div>
				   <div class="row-fluid">
					   <div class="span2" align="right"><div class="formlabel">Author</div></div>
					   <div class="span4"><input type="text" id="author" class="input-block-level" onchange="setAppFieldValue('author')"/></div>
					   <div class="span2" align="right"><div class="formlabel"><a href="#" class="tagLabel" data-original-title="Suggestions: country, region, time period, purpose">Tags</a></div></div>
					   <div class="span4"><textarea id="tags" rows="1" class="input-block-level" onchange="setAppFieldValue('tags')"></textarea></div>
				   </div>
				   <div class="row-fluid">
					   <div class="span2" align="right"><div class="formlabel">Def Label Style</div></div>
					   <div class="span4"><select id="defaultLabelStyle" class="input-block-level" onchange="setAppFieldValue('defaultLabelStyle')"><option value="labelStyle1" style="background: #FFFF00;">Yellow</option><option value="labelStyle2" style="background: #99FF66;">Green</option><option value="labelStyle3" style="background: #00FFFF;">Blue</option><option value="labelStyle4" style="background: #FF9933;">Orange</option><option value="labelStyle5" style="background: #FF8181;">Red</option><option value="labelStyle6" style="background: #E0E0EB;">Grey</option></select></div>
					   <div class="span2" align="right"><div class="formlabel">Anim Duration</div></div>
					   <div class="span4"><select id="animLength" class="input-block-level" onchange="setAppFieldValue('animLength')"><option value="5">5 sec</option><option value="10">10 sec</option><option value="15">15 sec</option><option value="20">20 sec</option><option value="30">30 sec</option><option value="45">45 sec</option><option value="60">60 sec</option></select></div>
				   </div>
			   </div> <!-- collapsible area -->
			   <!-- put other app rows and map here -->
			   <div class="row-fluid"> <!-- map center buttons -->
				   <div class="span3" align="right"><button type="button" name="setCenterButton" onclick="setCenter()">Set Center</button></div>
				   <div class="span3" align="center"><button type="button" name="setZoomButton" onclick="setZoom()">Set Zoom</button></div>
				   <div class="span3" align="left"><button type="button" name="gotoCenterButton" onclick="toCenter()">To Center</button></div>
				   <div class="span3" align="center"><select id="status" class="input-block-level" onchange="setAppFieldValue('status')"><option value="0">Private</option><option value="1">Public</option></select></div>
			   </div>
			   <div id="map_canvas" class="span12">map goes here</div>
		   </div>
		   <div id="pathDiv" class="span5"> <!-- path form area -->
		   </div>
	   </div>
<% end %>
</div>

app/views/replays/index.html.erb
<div class="row-fluid">
   <div id="search" class="span12 text"></div>
</div>

<div class="row-fluid">
   <div id="results" class="span7">
      <% @replays.each do |replay| %>
	<div class="row-fluid bordered">
	    <div align="center" class="span2">
		    <% if replay.screenshotPath != '' %>
                       <%= image_tag "replay.screenshotPath", :size => "50x38", :alt => replay.screenshotPath %>
	            <% else %>
                       <%= image_tag "default_thumbnail.jpg", :size => "50x38", :alt => replay.screenshotPath %>
		    <% end %>
             </div>
	     <div class="span8">
		     <b><%= link_to replay.name, replay %></b></br>
               <%= replay.desc %>
             </div>
             <div class="span2">
		     <div class="statistic">Views:</div><div class="statistic">Likes:</div>
             </div>
        </div>
      <% end %>
   </div>
   <div id="tagsAdsMessages" class="span5">
   </div>
</div>

app/views/replays/show.html.erb
<%= javascript_tag do %>
	var replayData=<%= raw @replaydata %>;
<% end %>

<%= javascript_include_tag "replay" %>

<div class="row-fluid">
	<div class="span12 text"><h3><%= @replay.name %><h3></div>
</div>

<div class="row-fluid">
   <div id="map_canvas" class="span12">map goes here</div>
</div>

<div class="row-fluid">
   <div class="span8"> <!-- info -->
	<div class="row-fluid">
		<div class="span2 small-text">Description:</div>
		<div class="span10"><%= @replay.desc %></div>
	</div>
	<div class="row-fluid">
		<div class="span2 small-text">Source:</div>
		<div class="span10"><%= @replay.source %></div>
	</div>
	<div class="row-fluid">
		<div class="span2 small-text">Replay creator:</div>
		<div class="span10"><%= @replay.attribution %></div>
	</div>
	<div class="row-fluid">
		<div class="span2 small-text">Length:</div>
		<div class="span10"><%= @replay.length %> seconds</div>
	</div>
   </div>
   <div class="span4"> <!-- stats -->
	<div class="row-fluid">
		<div class="span2 small-text">Views:</div>
		<div class="span10">TBD</div>
	</div>
	<div class="row-fluid">
		<div class="span2 small-text">Likes:</div>
		<div class="span10">TBD</div>
	</div>
   </div>
</div>

<p>

<% if user_signed_in? %>
	<% if current_user.id == @replay.userId %>
		<script type="text/javascript">
			function gotoEdit () {
			   window.location="<%= edit_replay_path(@replay) %>";
			}
		</script>
		<button type="button" id="saveButton" onclick="gotoEdit()">Edit Replay</button>
	<% end %>
<% end %>